import Link from "next/link";
import "./globals.css";
import { Manrope } from "next/font/google";
import Image from "next/image";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <header className="border- flex items-center justify-between bg-black-light px-6 py-8 text-white">
          <div>
            <Image
              src="/shared/tablet/icon-hamburger.svg"
              width={16}
              height={16}
              alt="mobile navigation menu icon"
            />
          </div>
          <div>
            <Image
              src="/shared/desktop/logo.svg"
              width={143}
              height={25}
              alt="audiophile logo"
            />
          </div>
          <div>
            <Image
              src="/shared/desktop/icon-cart.svg"
              width={20}
              height={20}
              alt="shopping cart icon"
            />
          </div>
        </header>
        <div className="seperator"></div>
        {children}
      </body>
    </html>
  );
}
